IMSv1/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using IMSv1.Models.Dtos;
using IMSv1.Repositories;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace IMSv1.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthRepository _repo;

        public AuthController(IAuthRepository repo)
        {
            _repo = repo;
        }
        
        // GET Login
        public IActionResult Login()
        {
            return View();
        }
        
        // POST Login
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginDto loginCreds)
        {
            var user = await _repo.Login(loginCreds);
            if (user == null)
            {
                return View();
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Name),
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                new Claim(ClaimTypes.Role, user.Role.ToString())
            };
            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var authProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                ExpiresUtc = DateTimeOffset.UtcNow.AddHours(1),
                IsPersistent = true,
                IssuedUtc = DateTimeOffset.Now
            };
            
            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
            return View("Profile", user);
        }

        [HttpGet]
        public IActionResult Profile()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

IMSv1/Controllers/ClientsController.cs
using System.Threading.Tasks;
using IMSv1.Extensions;
using IMSv1.Models;
using IMSv1.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IMSv1.Controllers
{
    [Authorize]
    public class ClientsController : Controller
    {
        private readonly IUsersRepository _repo;

        public ClientsController(IUsersRepository repo)
        {
            _repo = repo;
        }
        
        public async Task<IActionResult> Index()
        {
            var userId = HttpContext.GetUserId();
            var clients = await _repo.GetClientsForUser(userId);
            
            return View(clients);
        }

        [HttpPost]
        public async Task<IActionResult> AddPayment(int clientId, decimal amount)
        {
            amount *= 100;
            var intAmount = (int) amount;
            var userId = HttpContext.GetUserId();
            var res = await _repo.AddPayment(userId, clientId, intAmount);
            if (res)
            {
                return RedirectToAction("Success", "Home");
            }

            return RedirectToAction("Error", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> AddClient()
        {
            var users = await _repo.GetUsers(HttpContext.GetUserId());
            ViewData["users"] = users;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddClient(AddClientDto input)
        {
            var result = await _repo.AddClient(input, HttpContext.GetUserId());
            return RedirectToAction(result ? "Success" : "Error", "Home");
        }
    }
}

IMSv1/Controllers/TransactionsController.cs
using System;
using System.Threading.Tasks;
using IMSv1.Extensions;
using IMSv1.Models.Dtos;
using IMSv1.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IMSv1.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private readonly ITransactionsRepository _repo;
        private readonly IProductsRepository _productsRepository;
        private readonly IUsersRepository _usersRepository;

        public TransactionsController(ITransactionsRepository repo, 
            IProductsRepository productsRepository,
            IUsersRepository usersRepository)
        {
            _repo = repo;
            _productsRepository = productsRepository;
            _usersRepository = usersRepository;
        }
        
        public async Task<IActionResult> Index()
        {
            var userId = HttpContext.GetUserId();
            var transactions = await _repo.GetTransactions(userId);
            return View(transactions);
        }

        public async Task<IActionResult> GetTransaction(int tId)
        {
            var userId = HttpContext.GetUserId();
            var transaction = await _repo.GetTransaction(userId, tId);
            if (transaction == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var userClient = await _usersRepository.GetClient(userId, transaction.ToId);
            ViewData["client"] = userClient;
            return View("TransactionDetails", transaction);
        }

        [HttpGet]
        public async Task<IActionResult> PostTransaction()
        {
            var userId = HttpContext.GetUserId();
            var products = await _productsRepository.GetAllProducts(userId);
            ViewData["products"] = products;
            var users = await _usersRepository.GetUsers(userId);
            ViewData["users"] = users;
            Console.WriteLine(users.Count);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PostTransaction(NSTransactionDto newTransaction)
        {
            var userId = HttpContext.GetUserId();
            var isSuccessful = await _repo.AddTransaction(newTransaction, userId);

            if (isSuccessful)
            {
                return RedirectToAction("Success", "Home");
            }

            return RedirectToAction("Error", "Home");
        }
        
        [HttpGet]
        public async Task<IActionResult> PostReturn()
        {
            var userId = HttpContext.GetUserId();
            var products = await _productsRepository.GetAllProducts(userId);
            ViewData["products"] = products;
            var users = await _usersRepository.GetUsers(userId);
            ViewData["users"] = users;
            Console.WriteLine(users.Count);
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> PostReturn(NSTransactionDto newTransaction)
        {
            var userId = HttpContext.GetUserId();
            var isSuccessful = await _repo.AddTransaction(newTransaction, userId);

            if (isSuccessful)
            {
                return RedirectToAction("Success", "Home");
            }

            return RedirectToAction("Error", "Home");
        }
    }
}

IMSv1/Views/Shared/_Layout.cshtml
@using IMSv1.Extensions
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!doctype html>
<html lang="en">
<head>
    <title>IMS v1</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/custom.css">
</head>
<body>
<div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar" class="">
        <div class="custom-menu">
            <button type="button" id="sidebarCollapse" class="btn btn-primary">
                <i class="fa fa-bars" style="margin-left: -5px;"></i>
                <span class="sr-only">Toggle Menu</span>
            </button>
        </div>
        <div class="p-4">
            <h1>
                <a asp-controller="Home" asp-action="Index" class="logo">IMS v1</a>
            </h1>
            <ul class="list-unstyled components mb-5">
                <li class="@ViewData["home_active"]">
                    <a asp-controller="Home" asp-action="Index"><span class="fa fa-home mr-3"></span> Ana səhifə</a>
                </li>
                <li class="@ViewData["products_active"]">
                    <a asp-controller="Products" asp-action="Index"><span class="fa fa-tag mr-3"></span> Məhsullar</a>
                </li>
                <li class="@ViewData["inventory_active"]">
                    <a asp-controller="Inventory" asp-action="Index"><span class="fa fa-tags mr-3"></span> Anbar</a>
                </li>
                <li class="@ViewData["transactions_active"]">
                    <a asp-controller="Transactions" asp-action="Index"><span class="fa fa-shopping-cart mr-3"></span> Satışlar</a>
                </li>
                <li class="@ViewData["clients_active"]">
                    <a asp-controller="Clients" asp-action="Index"><span class="fa fa-users mr-3"></span> Müştərilər</a>
                </li>
                @{
                    if (!HttpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
                    {
                        <li class="@ViewData["login_active"]">
                            <a asp-controller="Auth" asp-action="Login"><span class="fa fa-user-circle mr-3"></span> Daxil olun</a>
                        </li>
                    }
                    else
                    {
                        <li class="@ViewData["logout_active"]">
                            <a asp-controller="Auth" asp-action="Logout">
                                <span class="fa fa-power-off mr-3"></span> Çıxış edin (@HttpContextAccessor.HttpContext.GetUserName())
                            </a>
                        </li>
                    }
                }
                <li class="@ViewData["about_active"]">
                    <a asp-controller="Home" asp-action="About"><span class="fa fa-info mr-3"></span> Haqqımızda</a>
                </li>
            </ul>

            <div class="mb-5">
                <h3 class="h6 mb-3">İstifadə etdiyiniz üçün təşəkkür edirik</h3>
                @* <form action="#" class="subscribe-form"> *@
                @*     <div class="form-group d-flex"> *@
                @*         <div class="icon"> *@
                @*             <span class="icon-paper-plane"></span> *@
                @*         </div> *@
                @*         <input type="text" class="form-control" placeholder="Email ünvanınızı daxil edin"> *@
                @*     </div> *@
                @* </form> *@
            </div>

            <div class="footer">
                <p>
                    Copyright &copy;<script>document.write(new Date().getFullYear().toString());</script> All rights reserved | Built with &hearts; by 
                    <a href="https://facebook.com/alvan.rahimli" style="color: white">Alvan&nbsp;Rahimli</a>
                </p>
            </div>

        </div>
    </nav>

    <!-- Page Content  -->
    <div id="content" class="p-4 p-md-5 pt-5">
        @RenderBody()
    </div>
</div>

<script src="~/js/jquery.min.js"></script>
<script src="~/js/popper.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/main.js"></script>
@(await RenderSectionAsync("Scripts", false))
</body>
</html>